### ISSUE TITLE
unable to add toolbox to recent version of matlab

### ISSUE THREAD

**Issue by SamarEng** [pnanez/HyEQ_Toolbox#100]
Hi, Could you help me pls? I tried to add the last version of hybrid toolbox to matlab but it has an error of not being able to read getting started file of this toolbox. I tried different source folder paths by Add-on as it was recommended. No difference. Matlab version is the last released 2023b. Thanks in advance.

![Untitled](https://github.com/pnanez/HyEQ_Toolbox/assets/147251077/9822c007-ccb3-42c9-8b08-103abe246b70)
1ccabce31fc)

**Comment by pwintz** [comment]
Hey Samar, I just installed the HyEQ toolbox on R2023b. Getting Started and `hybrid.tests.run()` worked for me, so something about your particular system or installation process is causing problems.  Can you provide the following info to help me understand the problem?
* Did you install the add-on through the MATLAB add-on explorer?
* What OS are you using? 
* What happens when you run `hybrid.tests.run()` the following command in the command line?
* Outside of MATLAB, can you open this file? 
![image](https://github.com/pnanez/HyEQ_Toolbox/assets/19618780/c514cb7c-219b-48d1-9768-4d82427bc9da)

**Comment by SamarEng** [comment]
Hi Paul. Yes, using add-on explorer, I had the problem. Good news is that I could install the toolbox file directly without using add-ons. and I could ran hybrid.tests.run() with no problem. Thank you.
