### ISSUE TITLE
Initialization algorithm for algebraic loops - simulink

### ISSUE THREAD

**Issue by pnanez** [pnanez/HyEQ_Toolbox#35]
Closed loops might generate algebraic loops, and such loops require that the IC fulfill such algebraic equations. Simulink has different algorithms to do that, we need to test this and understand how and when to use those algorithms.

**Comment by pwintz** [comment]
I say that we move this to the Version 3.1 project or close it. I don't think we'll have time for it before we release v3.0.

**Comment by pwintz** [comment]
We can break algebraic loops by using the "x-" output from Hybrid Systems. I've changed the implementation of the Hybrid System blocks a bit so that x- is set to the x output with a memory block that adds a delay of one integration step. I believe this is the same as using 'x-' output by the integrator system, but using the output from the integrator system sometimes caused Simulink to complain.

**Comment by pwintz** [comment]
Closing this as it seems to no longer be a problem. We'll reopen if anybody runs into a problem with Algebraic loops again.
