### ISSUE TITLE
hybrid time domain in Simulink

### ISSUE THREAD

**Issue by pnanez** [pnanez/HyEQ_Toolbox#47]
There is a fundamental problem about how we are logging time in Simulink.
For just one system the htd works fine, but when several HS are interconnected, or even in the same model, some unexpected behavior appears.
The source of the problem is that each HS has its own htd, which in principle is ok, but the issue is that there is no correlation between those htds. 
One example to show the problem might be the following,
Assume a bouncing ball where the position of the floor is given by the output of another HS- (HS1).
Let's assume that the output of HS1 is a staircase, where the position of the floor is decreased every T seconds.
If we set T>Z where Z is the zeno time for the ball for a given initial condition, then the simulation should stop by reaching the maximun number of jumps.
This might not happen since the htd of both systems are not related at all.
I haven't created this example, but, as far as I have tested similar problems, this might be a good way to describe the problem and test solutions.

**Comment by pwintz** [comment]
Each HyEQ Simulink block has its own `J` parameter that determines the maximum number of jumps. If that block jumps `J` times, then it terminates the entire simulation because of the stop logic: 

![image](https://user-images.githubusercontent.com/19618780/195982289-50e6217d-dfc9-4999-be84-052f07fae97b.png)
