### ISSUE TITLE
Update or remove CopyFnc callback functions in Simulink 

### ISSUE THREAD

**Issue by pnanez** [pnanez/HyEQ_Toolbox#49]
Most of the call back functions in the blocks are now not functional in 2018 and up, most of them does not have sense now, i.e., set the simulation time to T, we need to review which call back functions make sense and purge the rest.

**Comment by pwintz** [comment]
Instead of using callback functions in blocks, I suggest we switch to using callbacks defined in the model properties (File > Model Properties > Model Properties > Callbacks). The PreLoadFcn callback is run when the model is opened, so it can be used to run the initialization script. The StopFcn callback runs each time a simulation finishes, so it can be used to run the postprocessing script.

**Comment by pwintz** [comment]
Here is a comment from Pablo regarding the CopyFnc callback:

> I feel that changing the simulation stop time as T whenever you drag an HS block is too intrusive, sometimes, even I forget about that feature, and that forced change is annoying, particularly if you have your settings/variables in place.

In a subsequent version of the toolbox, I think we should remove these callbacks or add a dialog prompt that asks users before making the change.

**Comment by pwintz** [comment]
I need to add some documentation for the dialog box that opens when a Simulink HyEQ block is added. Otherwise, this is all done.

**Comment by pwintz** [comment]
Created `hybrid.internal.onSimulinkBlockCopy` function that is called by all of the HyEQ blocks when they are copied. In the future, we can modify that function instead of editing the blocks one by one.
When called, `onSimulinkBlockCopy` asks the user to set the value of `maxStep`. 

For blocks that users must modify the internal block structure, there is also an `'no link'` option that tells `onSimulinkBlockCopy` to break the link from the copied block to the library block.
