### ISSUE TITLE
m2tex required to compile help tex files

### ISSUE THREAD

**Issue by pnanez** [pnanez/HyEQ_Toolbox#53]
I forgot to mention that in order to create the help files (in tex), we pull the comments from the .m functions and create tex files that are used in the main help document. This is also used with the "help and description" text of all examples.
The idea is to modify the .m, then from the .m generate small .tex that can be used to create the main documentation file. The main function that does that is:  RebuildTexFiles.m located at \HybridSimulator\helpFiles\Instructions_Main.
That function uses m2tex, which is not ours, so you have to install it beforehand! 
here is the link:
https://www.mathworks.com/matlabcentral/fileexchange/5010-m2tex
Notice that in 2015 I made a comment about a change that I have to made... check the comments.

**Comment by pwintz** [comment]
I've reworked the .tex files and compilation process so that we no longer need to convert the .m files to .tex. Instead, I've used the `listings` package to include MATLAB files and use `make4ht` to compile. See [this StackExchange question](https://tex.stackexchange.com/questions/631906/include-matlab-code-listing-compiled-into-html-with-correct-colors/632286) for details.

To compile the HTML files in the dev branch now, simply run `. ./GenerateHtmlfiles.sh` in the directory `helpFiles\Instructions_Main`.
