### ISSUE TITLE
Question about the definition of sets C and D for a bouncing ball example, in particular about their boundaries

### ISSUE THREAD

**Issue by hurak** [pnanez/HyEQ_Toolbox#83]
Perhaps neither a bug nor an issue, therefore I am placing it into the help request category.

In the example(s) with a bouncing ball the flow and jump sets C and D are defined as (x1 >= 0 && x2 >= 0), and (x1 <= 0 && x2 <= 0), respectively. 

But In the book Goebel, Rafal, Ricardo G. Sanfelice, and Andrew R. Teel. Hybrid Dynamical Systems: Modeling, Stability, and Robustness. Princeton University Press, 2012, on which this toolbox is certainly based, the C and D sets - as developed on page 3 - are such that C is composed of the OPEN upper half-line AND the nonnegative x2 axis, that is, x1>0 or (x1=0 and x2>=0), and then D set is defined as the negative part of the x2 axis, that is, x1=0 and x2<0.

The difference between the conditions in the code and thise in the book are obviously in two aspects: 

1. whether or not negative heights are allowed at all, 
2. whether the negative real axis belongs to the flow set.

I find the version in the book correct - as soon as the ball hits the ground (x1=0 and x2<0), it can no longer flow, it MUST jump.

I guess that that there may be two practical explanations why it is not necessary to bother here with these details: 

1. when it comes to detecting an event in a numerical solver, we are forced to use inequalities rather then equations as the event conditions, 
2. even though there is now an overlap between C and D (on the negative x1 axis), there is a mechanism in the toolbox that determines which of the two conditions has a PRIORITY. 

But still, I find it a bit confusing and It might deserve some discussion in the manual, I guess. But maybe I am just too much rooted in the hybrid automata framework in which the "priorities" between the domain sets and guard sets are not to be determined by the user but most literature defines the guard condition as the JUMP (aka transition) ENABLING (aka necessary) condition while the satisfaction of the domain (aka mode invariant) condition is the necessary condition for FLOW (as long as the condition is satisfied, a transition/jump is not enforced).

Let me explain the apparent pedantry here: I am just preparing for teaching this material, hence I am trying to anticipate any remarks, questions and objections. That is why I would like to ask for a comment on this issue. Many thanks in advance.

**Comment by pwintz** [comment]
The definition of the bouncing ball system given in _Hybrid Dynamical Systems_, p.3 works analytically but runs into numerical problems. In particular,

- Using `C = {(x1, x2) | x1 > 0 or (x1 = 0 and x2 > 0)` and `D = {(x1, x2) | x1 = 0 and x2 < 0)` fails because the numerical solver cannot identify the exact time when the state hits the negative x2-axis, so it overshoots it slightly. This would make x1 less than zero, which is not in C or D, causing numerical solutions to terminate.
- In general, we want C and D to be closed sets, otherwise, the hybrid system is not well-posed (see Assumption 6.5 and the following results in _Hybrid Dynamical Systems_).

> I find the version in the book correct - as soon as the ball hits the ground (x1=0 and x2<0), it can no longer flow, it MUST jump.

When using `C = {(x1, x2) | x1 >= 0 or x2 >= 0)` and `D = {(x1, x2) | x1 <= 0 or x2 <= 0)`, if the ball is at the ground (x1 = 0) and either stationary or moving downward (x2 <= 0), then the ball must jump because flowing would immediately move the ball out of the flow set. Formally, speaking, for all x \in C\cap D, the flow map is not in the tangent cone of C at x:  f(x) ∉ T_C(x). See Chapter 5 for more details, esp. Lemma 5.26(a).

For a general explanation of some of the numerical pitfalls that you should be aware of when using the HyEQ Toolbox, see _The HyEQ Simulink Library_ > _Behavior in the Intersection of C and D_  in the documentation.
