### ISSUE TITLE
Error when plotting with Marker Symbols using the HybridPlotBuilder

### ISSUE THREAD

**Issue by ryan-sean-johnson** [pnanez/HyEQ_Toolbox#91]
The plot() function returns the following error when a marker symbol (*, ., o, +, etc.) is used as the flowLineStyle or the jumpLineStyle in the HybridPlotBuilder.

```
Error using plot
'*' is not a valid value. Use one of these values: '-' | '--' | ':' | '-.' | 'none'.
```

**To Reproduce**
The following script reproduces the error using the marker symbol '*'

```
figure;
t = linspace(0,2*pi)';
x = sin(t);
sol = HybridArc(t,0*t,x);

HybridPlotBuilder()...
    .flowLineStyle('*')...
    .plotFlows(sol)
```

**Expected behavior**
The HybridPlotBuilder should plot flows and jumps with the specified marker symbol.

**Desktop:**
 - OS: Windows 11 Pro
 - MATLAB Version: 2019b
 - Hybrid Toolbox Version: 3.0.0.76

**Comment by pwintz** [comment]
It would be quick and easy to support users setting flow markers using a new function `HybridPlotBuilder.flowMarker`. Making the `flowLineStyle` support markers would be more involved because we'd have to parse the argument for the marker portion and the line style portion. 

We pass the line style as a name-value argument `'LineStyle', this.flow_line_style`. To add support for markers, we could add the following argument: `'Marker', this.flow_marker`.
